---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: allocate a new elastic IP without associating it to anything
    ec2_eip:
      state: present
      region: us-east-1
      tag_name: name
      tag_value: iacstart
    register: eip
