---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: associate an elastic IP with an instance
    ec2_eip:
      instance_id: "{{ device_id }}"
      ip: "{{ ip }}"
      region: "{{ region }}"
      allow_reassociation: yes
