---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  # - name: create RDS subnet group
  #   rds_subnet_group:
  #     name: iac-rds-group
  #     state: present
  #     description: IAC RDS Subnet Group
  #     region: "{{ region }}"
  #     subnets:
  #      - "{{ vpc_subnet_id }}"
  #   register: iac_rds_subnet_group

  - name: create database security group
    ec2_group:
      name: iac-database-access
      description: HTTPS, SSH, Psql and Redis access
      region: "{{ region }}"
      vpc_id: "{{ vpc_subnet_id }}"
      rules:
        - proto: tcp
          ports:
            - 5432
            - 6379
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
            - 5432
            - 6379
          cidr_ip: 0.0.0.0/0
    register: rds_sec_group_db_access

  - name: create database with RDS
    rds_instance:
      state: present
      engine: mariadb
      db_instance_class: db.t3.small
      db_instance_identifier: iac-db
      username: "mariadb"
      password: "mariadbpw"
      db_name: "iacdb"
      allocated_storage: 20
      vpc_security_group_ids:
        - "{{ rds_sec_group_db_access.group_id }}"
      region: "{{ region }}"
    register: rds_instance