---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Find instance by tag 
    ec2_instance_info:
      region: "{{ region }}"
      filters:
        "tag:Deployment": "iacstart"
    register: ec2_instances

    debug:
      vars: ec2_instances

  - name: Terminate EC2 instances
    ec2:
      region: "{{ region }}"
      instance_ids: "{{ item }}"
      state: 'absent'
      wait: yes
    with_items: "{{ ec2_instances.id }}"

  - name: Delete VPC
    ec2_vpc_net:   
      name: "{{ vpc }}"  
      cidr_block: "{{ vpc_cidr }}"  
      region: "{{ region }}"  
      state: absent  
      purge_cidrs: yes  
    register: vpc_delete
