---

- hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: true

  vars:
  #  mysql_packages:
  #    - python-mysqldb

    mysql_root_password: super-secure-password
    mysql_users:
      - name: webshop
        password: superSECR3T
        state: present
        host: "%"
        priv: "*.*:ALL,GRANT"
    mysql_databases:
      - name: webshop
        encoding: utf8
        collation: utf8_general_ci

  pre_tasks:
    - name: Install MySQL Python Packages
      apt: 
        name: ['python3-pip', 'python3-mysqldb', 'python-mysqldb']
        state: present
        update_cache: yes

  roles:
    - role: geerlingguy.mysql
    #- role: ansible-role-mysql
      become: yes
