---
- hosts: all
  gather_facts: false
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install Software
      apt:
        pkg:
          - nfs-common
        update_cache: true
      
    - name: Create Mount Point
      file:
        path: "/mnt/images"
        state: directory
        owner: "{{ ansible_ssh_user }}"
      
    - name: Mount NetApp NFS Share
      mount: 
        path: /mnt/images
        src: 10.10.10.4:/elated-fervent-engelbart
        fstype: nfs
        opts: ro,hard,rsize=65536,wsize=65536,vers=3,tcp
        state: present

