---
- hosts: all
  gather_facts: false

  tasks:
    - name: Install Software
      apt:
        pkg:
          - nfs-common
        update_cache: true
      
    - name: Create Mount Point
      file:
        path: "/opt/iac_shop/public/images/robo"
        state: directory
        owner: "{{ ansible_ssh_user }}"
      
    - name: Mount NetApp NFS Share
      mount: 
        path: /opt/iac_shop/public/images/robo
        src: 10.10.10.4:/elated-fervent-engelbart
        fstype: nfs
        opts: ro,hard,rsize=65536,wsize=65536,vers=3,tcp
        state: present